version: '3.7'
services:
  moi-database:
    image: mysql:5.7
    container_name: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  moi-app-qa:
    image: moi-project
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:9091"
    depends_on: 
      - moi-database
    restart: on-failure

