version: '3.7'
services:
  moi-database:
    image: mysql:5.7
    container_name: moi-db-compose
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - moi-database:/var/lib/mysql
  moi-app:
    build: .
    image: moi-project
    container_name: moi-app-compose
    ports:
      - "9092:9091"
    volumes:
      - moi-project:/source/tempdata
    depends_on: 
      - moi-database
    restart: on-failure

volumes:
    moi-database:
        name: moi-database
    moi-project:
        name: moi-project
