version: '3.7'
services:
  moi-database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
  moi-app:
    build: .
    image: moi-project
    ports:
      - "${APP_PORT}:9091"
    depends_on: 
      - moi-database
    restart: on-failure

