spring:
  datasource:
    url: jdbc:mysql://192.168.0.108:33061/mysql
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
